### ISSUE TITLE
Traceback when dragging/dropping song from existing playlist

### ISSUE THREAD

**Issue by fgvanzee** [exaile/exaile#625]
When dragging and dropping a song from an existing playlist A (or "Entire Library") to playlist B (via the entry for playlist B in the left-hand playlist pane, not directly to the tab for playlist B), Exaile throws a traceback error and fails to add the song to playlist B.

### Steps to Reproduce (for bugs)
I just upgraded from 3.4.5, so I had plenty of existing playlists. After having added a song to my collection (via a scan from a smart playlist), I wanted to add that song to a different (non-smart) custom playlist. The following steps worked in 3.4.5.
1. Add song to collection ("Entire Library").
2. Find song in collection / smart playlist A.
3. Drag song from currently active playlist A tab and drop over the title of playlist B in left-hand playlist pane.

### Expected Behavior
The expected behavior is for the song to be added to playlist B on which it is dropped (and also for it to remain in playlist A).

### Current Behavior
In the terminal in which Exaile is launched, I get the following error message:
```
Traceback (most recent call last):
  File "/usr/lib64/exaile/xlgui/panel/playlists.py", line 644, in drag_data_received
    self._drag_data_received_uris(tv, context, x, y, selection, info, etime)
  File "/usr/lib64/exaile/xlgui/panel/playlists.py", line 696, in _drag_data_received_uris
    if context.action == Gdk.DragAction.MOVE:
AttributeError: 'X11DragContext' object has no attribute 'action'
```
The outcome is the same regardless of whether I drag/drop from the "Entire Library" playlist or a smart playlist.

### Possible Solution
This is my first bug report to Exaile, and I'm unfamiliar with the code, so I'm afraid I can't offer any suggested explanations or fixes.

### Environment
* Operating System and version: Gentoo (Linux kernel 5.0.7)
* Exaile Version: 4.0.0rc3
* Dependencies:
   - GStreamer: 1.14.4
   - GTK+: 3.24.4
   - Locale: en_US UTF-8
   - Mutagen: 1.40.0
   - PyGObject: 3.28.3
   - Python: 2.7.15

**Comment by sjohannes** [comment]
Thanks, this should be fixed in the next release. The UI is still broken (see #627) but the track should be added correctly.
